apt update

apt install -y git python3 python3-pip python3-venv vim
git clone https://github.com/Anil-matcha/AI-Youtube-Shorts-Generator.git
cd AI-Youtube-Shorts-Generator

python3 -m venv .
source bin/activate
pip3 install -r requirements-local.txt
